require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe MeetController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Meet. As you add validations to Meet, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MeetsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all meets as @meets" do
      meet = Meet.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:meets)).to eq([meet])
    end
  end

  describe "GET show" do
    it "assigns the requested meet as @meet" do
      meet = Meet.create! valid_attributes
      get :show, {:id => meet.to_param}, valid_session
      expect(assigns(:meet)).to eq(meet)
    end
  end

  describe "GET new" do
    it "assigns a new meet as @meet" do
      get :new, {}, valid_session
      expect(assigns(:meet)).to be_a_new(Meet)
    end
  end

  describe "GET edit" do
    it "assigns the requested meet as @meet" do
      meet = Meet.create! valid_attributes
      get :edit, {:id => meet.to_param}, valid_session
      expect(assigns(:meet)).to eq(meet)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Meet" do
        expect {
          post :create, {:meet => valid_attributes}, valid_session
        }.to change(Meet, :count).by(1)
      end

      it "assigns a newly created meet as @meet" do
        post :create, {:meet => valid_attributes}, valid_session
        expect(assigns(:meet)).to be_a(Meet)
        expect(assigns(:meet)).to be_persisted
      end

      it "redirects to the created meet" do
        post :create, {:meet => valid_attributes}, valid_session
        expect(response).to redirect_to(Meet.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved meet as @meet" do
        post :create, {:meet => invalid_attributes}, valid_session
        expect(assigns(:meet)).to be_a_new(Meet)
      end

      it "re-renders the 'new' template" do
        post :create, {:meet => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested meet" do
        meet = Meet.create! valid_attributes
        put :update, {:id => meet.to_param, :meet => new_attributes}, valid_session
        meet.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested meet as @meet" do
        meet = Meet.create! valid_attributes
        put :update, {:id => meet.to_param, :meet => valid_attributes}, valid_session
        expect(assigns(:meet)).to eq(meet)
      end

      it "redirects to the meet" do
        meet = Meet.create! valid_attributes
        put :update, {:id => meet.to_param, :meet => valid_attributes}, valid_session
        expect(response).to redirect_to(meet)
      end
    end

    describe "with invalid params" do
      it "assigns the meet as @meet" do
        meet = Meet.create! valid_attributes
        put :update, {:id => meet.to_param, :meet => invalid_attributes}, valid_session
        expect(assigns(:meet)).to eq(meet)
      end

      it "re-renders the 'edit' template" do
        meet = Meet.create! valid_attributes
        put :update, {:id => meet.to_param, :meet => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested meet" do
      meet = Meet.create! valid_attributes
      expect {
        delete :destroy, {:id => meet.to_param}, valid_session
      }.to change(Meet, :count).by(-1)
    end

    it "redirects to the meets list" do
      meet = Meet.create! valid_attributes
      delete :destroy, {:id => meet.to_param}, valid_session
      expect(response).to redirect_to(meets_url)
    end
  end

end
